# -*- coding: utf-8 -*-
"""reco.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIUcdvWLBdxKlTpUDX8hTv8WzvaTKMP_

1. Download new .mid files at Musescore.com and upload them to my Google Drive.  

2. Only edit or input file name below.  Include .mid in file name.  For instance 'CdL.mid'.

3. Go to the Runtime tab above and click "run all".  

4.  After running the code, the corresponding .mp3 file will also be placed within the folder where you saved the .mid file.

There are still a few bugs here and there that I encounter - usually with an unknown instrument or some other error within the midi messages - so if it doesn't work for a song, I apologize, but please find another song and try again.
"""

mid_file = 'Shallow_A_star_is_born_Lady_Gaga_Bradley_Cooper_final.mid'

# Google Colab specific code commented out for standalone use
# from google.colab import drive
# drive.mount('/content/gdrive')

# !pip install mido
import mido
import numpy as np
import os
from scipy.io.wavfile import read, write

class table():
    def __init__(self):
        '''returns dictionary where instrument name and if it decays in amplitude are returned.
        Additionally, use of available decay is returned'''
        self.tab = {1: ['acounstic grand piano', True, True],
                    2: ['bright acoustic piano', True, True],
                    3: ['electric grand piano', False, True],
                    4: ['honky-tonk piano', True, True],
                    5: ['electric piano 1', False, True],
                    6: ['electric piano 2', False, True],
                    7: ['harpsichord', True, True],
                    8: ['clavinet', False, True],
                    9: ['celesta', True, True],
                    10: ['glockenspiel', True, True],
                    11: ['music box', True, True],
                    12: ['Vibraphones', True, True],
                    13: ['Marimbas', True, True],
                    14: ['Xylophones', True, True],
                    15: ['Tubular Bells', True, True],
                    16: ['Dulcimer/Santur', True, True],
                    17: ['Drawbar Organ 1', False, True],
                    18: ['Percussive B3 Organ 1', False, True],
                    19: ['Rock Organ', False, True],
                    20: ['Church Organ 1', False, True],
                    21: ['Reed Organ', False, True],
                    22: ['French Accordion', False, False],
                    23: ['Harmonica', False, False],
                    24: ['Bandoneon', False, False],
                    25: ['Nylon-Strings Guitar 1', False, False],
                    26: ['Steel-Strings Guitar', False, False],
                    27: ['Jazz Guitar', False, False],
                    28: ['Clean Electric Guitar', True, False],
                    29: ['Muted Electric Guitar', False, False],
                    30: ['Overdriven Guitar', False, False],
                    31: ['Distortion Guitar', False, False],
                    32: ['Guitar Harmonics', True, False],
                    33: ['Acoustic Bass', True, False],
                    34: ['Fingered Bass', True, False],
                    35: ['Picked Bass', True, False],
                    36: ['Fretless Bass', True, False],
                    37: ['Slapped Bass 1', True, False],
                    38: ['Slapped Bass 2', True, False],
                    39: ['Synth-Bass 1', False, True],
                    40: ['Synth-Bass 2', False, True],
                    41: ['Violin', False, False],
                    42: ['Viola', False, False],
                    43: ['Cello', False, False],
                    44: ['Contrabass', False, False],
                    45: ['Tremelo', False, False],
                    46: ['Pizzicato', True, False],
                    47: ['Harp', True, True],
                    48: ['Timpani', True, False],
                    49: ['Strings Ensemble 1', False, False],
                    50: ['Strings Ensemble 2', False, False],
                    51: ['Synth-Strings 1', False, False],
                    52: ['Synth-Strings 2', False, False],
                    53: ['Choir Aahs 1', False, False],
                    54: ['Voice Oohs', False, False],
                    55: ['Synth-Voices', False, False],
                    56: ['Orchestral Hits', False, False],
                    57: ['Trumpet', False, False],
                    58: ['Trombone 1', False, False],
                    59: ['Tuba', False, False],
                    60: ['Muted Trumpet 1', False, False],
                    61: ['French Horns 1', False, False],
                    62: ['Brass Section 1', False, False],
                    63: ['Synth-Brass 1', False, False],
                    64: ['Synth-Brass 2', False, False],
                    65: ['Soprano Saxophone', False, False],
                    66: ['Alto Saxophone', False, False],
                    67: ['Tenor Saxophone', False, False],
                    68: ['Baritone Saxophone', False, False],
                    69: ['Oboe', False, False],
                    70: ['English Horn', False, False],
                    71: ['Bassoon', False, False],
                    72: ['Clarinet', False, False],
                    73: ['Piccolo', False, False],
                    74: ['Flute', False, False],
                    75: ['Recorder', False, False],
                    76: ['Pan Flutes', False, False],
                    77: ['Bottles Blown Flutes', False, False],
                    78: ['Shakuhachi', False, False],
                    79: ['Whistle', False, False],
                    80: ['Ocarina', False, False],
                    81: ['Square Lead', False, False],
                    82: ['Saw Lead', False, False],
                    83: ['Synth Calliope', False, False],
                    84: ['Chiffer Lead', False, False],
                    85: ['Charang', True, False],
                    86: ['Solo Synth Vox', False, False],
                    87: ['5th Saw Wave', False, False],
                    88: ['Bass & Lead', True, False],
                    89: ['Fantasia Pad', True, True],
                    90: ['Warm Pad', True, True],
                    91: ['made up', False, False],
                    92: ['made up', False, False],
                    93: ['made up', False, False],
                    94: ['made up', False, False],
                    95: ['made up', False, False],
                    96: ['made up', False, False],
                    97: ['made up', False, False],
                    98: ['made up', False, False],
                    99: ['made up', False, False],
                    100: ['made up', False, False],
                    101: ['made up', False, False],
                    102: ['made up', False, False],
                    103: ['made up', False, False],
                    104: ['made up', False, False],
                    105: ['made up', False, False],
                    106: ['made up', False, False],
                    107: ['made up', False, False],
                    108: ['made up', False, False],
                    109: ['made up', False, False],
                    110: ['made up', False, False],
                    111: ['made up', False, False],
                    112: ['made up', False, False],
                    113: ['made up', False, False],
                    114: ['made up', False, False],
                    115: ['made up', False, False],
                    116: ['made up', False, False],
                    117: ['made up', False, False],
                    118: ['made up', False, False],
                    119: ['made up', False, False],
                    120: ['made up', False, False],
                    121: ['made up', False, False],
                    122: ['made up', False, False],
                    123: ['made up', False, False],
                    124: ['made up', False, False],
                    125: ['made up', False, False],
                    126: ['made up', False, False],
                    127: ['made up', False, False]
                    }

class set_note():
    def __init__(self,msg,inst,custom_note_mod=0,custom_perc_mod=0,
                 standard_offset=21,percussion_chan0=9,percussion_chan1=16,
                 sample_freq=44100, note_sec=4.0, standard_A4=440.0,
                 tmx=32767, tmn=-32768, max_v=127, n_ramp=1/200):
        self.iset = inst
        self.msg = msg
        self.pc0 = percussion_chan0
        self.pc1 = percussion_chan1
        self.cnm = custom_note_mod
        self.cpm = custom_perc_mod
        self.so = standard_offset
        self.standard_A4 = standard_A4
        self.tmx = tmx / max_v
        self.tmn = tmx / max_v
        self.x = np.arange(0, note_sec, 1 / sample_freq).reshape([1,-1])
        z = np.arange(n_ramp * sample_freq)
        z = np.exp(z / (z.shape[0] - 1)) - 1
        self.ramp = z / np.max(z)
        self.note_max = 0
        self.note_min = 300
        self.perc_max = 0
        self.perc_min = 300
        self.note_set()

    def note_set(self):
        self.noteset = {}
        for k in self.iset:
            r = self.msg[self.msg[:,0]==k]
            h = np.unique(r[:,1])
            if h.shape[0] != 0:
                if k != self.pc0 and k != self.pc1:
                    if np.max(h) - self.so > self.note_max:
                        self.note_max = np.max(h) - self.so
                    if np.min(h) - self.so < self.note_min:
                        self.note_min = np.min(h) - self.so
                    self.noteset[k] = [self.iset[k],h]
                else:
                    if np.max(h) > self.perc_max:
                        self.perc_max = np.max(h)
                    if np.min(h) < self.perc_min:
                        self.perc_min = np.min(h)
                    self.noteset[k] = [self.iset[k],h]
        self.note_char()
        self.notes_dict()

    def note_char(self):
        t = table().tab
        self.nchar = {}
        for k in self.noteset:
            if k != self.pc0 and k != self.pc1:
                self.nchar[k] = t[self.noteset[k][0]+1]
            else:
                self.nchar[k] = ['percussion', True, True]

    def notes_dict(self):
        self.notetab = {}
        self.coefphase = {}
        for k in self.noteset:
            if k != self.pc0 and k != self.pc1:
                self.coefphase[k] = self.rando()
                self.notetab[k] = self.gen_notes(k)
            else:
                self.notetab[k] = self.gen_perc(k)

    def gen_notes(self,k):
        sig = {}
        for g in self.noteset[k][1]:
            freq = self.note_freqs(g)
            s = self.signal(freq,k)
            if self.nchar[k][0] == True:
                s = s / np.exp(4 * self.x.flatten())
            sig[g] = s
        return sig

    def gen_perc(self,k,link='/content/gdrive/My Drive/mp5/midi/mperc/'):
        from scipy.io.wavfile import read
        sig = {}
        for g in self.noteset[k][1]:
            try:
                fs, s = read(link + str(int(g + self.cpm)) + '.wav')
                s = np.float64(s)
                if len(s.shape) != 1:
                    s = np.sum(s, axis=1)
                mx = np.max(s)
                mn = np.min(s)
                if mx >= np.abs(mn):
                    s = s / mx * self.tmx
                else:
                    s = s / mn * self.tmn
                sig[g] = s
                return sig
            except:
                print('instrument does not exist as a standard midi percussion instrument')
                return np.array([0])

    def note_freqs(self, note_idx):
        '''returns frequency of note; input index of note based on piano with
        88 keys, with A4=440; however, any index above or below would also be computed'''
        idx = note_idx - self.so + self.cnm
        note_A0 = self.standard_A4 / 16
        return note_A0 * 2 ** (idx / 12)

    def rando(self,harm=11):
        r = np.random.randint(2,harm+1)
        x = np.arange(0,harm+1)
        y = -0.81 * x / harm + 1
        h = np.random.uniform(-0.97,0.97,harm)
        y[1:] = y[1:] * h
        coef = y.reshape([-1,1])
        phase = np.random.uniform(-np.pi/2,np.pi/2,harm+1).reshape([-1,1])
        f = (x + 1).reshape([-1,1])
        return coef[:r], phase[:r], f[:r]

    def signal(self,f,k):
        cp = self.coefphase[k]
        y = cp[0]
        phase = cp[1]
        fk = cp[2]
        freq = fk * f
        x = y * np.sin(2 * np.pi * np.dot(freq,self.x) + phase)
        x = np.sum(x, axis=0)
        y = self.ramp.shape[0]
        x[:y] = x[:y] * self.ramp
        mx = np.max(x)
        mn = np.min(x)
        if mx >= np.abs(mn):
            x = x / mx * self.tmx
        else:
            x = x / mn * self.tmn
        if self.nchar[k][1]:
            x = x / np.exp(4 * self.x.flatten())
        return x

class midi_io():
    def __init__(self, fs=44100, tm=1/25, tmx=32767, tmn=-32768, vel_mx=127,
                 note_sec=6.0, perc_chan_0=9, perc_chan_1=16, standard_offset=21,
                 standard_A4=440.0,n_ramp=1/200):
        '''percussion channels are reserved for channel 10/17 - in python, this is coded 9/16'''
        self.fs = fs
        self.tmx = tmx
        self.tmn = tmn
        self.vel_mx = vel_mx
        self.ns = note_sec
        self.pc0 = perc_chan_0
        self.pc1 = perc_chan_1
        self.so = standard_offset
        self.a4 = standard_A4
        self.nr = n_ramp
        self.stm = np.int64(fs * tm)
        x = np.arange(self.stm)
        x = -x / self.stm + 1
        self.trunk = x
        self.tm = tm

    def midi_msg(self, link, custom_note=0,custom_perc=0):
        self.q = parser(link)
        z = set_note(self.q.msg,self.q.inst,custom_note,custom_perc,
                     self.so,self.pc0,self.pc1,self.fs,self.ns,self.a4,
                     self.tmx,self.tmn,self.vel_mx,self.nr)
        self.nt = z.notetab
        self.char = z.nchar
        self.cp = z.coefphase

    def dummy(self):
        samp = np.int64(np.ceil(self.q.mx * self.fs))
        return np.zeros([samp])

    def truncate(self, d, dur):
        if np.int64(dur * self.fs) >= self.trunk.shape[0]:
            p = np.int64(dur * self.fs)
            if d.shape[0] > p:
                d = d[:p]
                d[-self.q:] = d[-self.q:] * self.trunk
                return d
            else:
                return d
        else:
            return np.array([0])

    def scale(self, m):
        rmn = np.min(m)
        rmx = np.max(m)
        if rmx > self.tmx or rmn < self.tmn:
            if rmx >= np.abs(rmn):
                m = m / rmx * self.tmx
            else:
                m = m / rmn * self.tmn
        return np.int16(m)

    def decaystart(self,w,s):
        if s < w.shape[0]:
            y = w.shape[0] - s
            x = np.arange(0, y) / self.fs
            w[-y:] = w[-y:] / np.exp(4 * x)
            return w
        else:
            return w

    def reco(self):
        b = self.dummy()
        for k in range(self.q.msg.shape[0]):
            chan = self.q.msg[k,0]
            note_id = self.q.msg[k,1]
            vel = self.q.msg[k,2]
            try:
                w = vel * self.nt[chan][note_id]
                x = w.shape[0]
                y = np.int64(self.q.msg[k,3] * self.fs)
                z = np.int64(self.q.msg[k,5] * self.fs)
                t = np.int64(self.q.msg[k,4] * self.fs)
                if self.char[chan][1] == False and self.char[chan][2] == True:
                    w = self.decaystart(w,y)
                if self.char[chan][2] == True: #saying will decay after note_len; use column 5 of msg
                    if x >= z and self.q.msg[k,5] >= self.tm:
                        w = w[:z]
                        w[-self.stm:] = w[-self.stm:] * self.trunk
                        x = w.shape[0]
                        b[t:t+x] = b[t:t+x] + w
                    elif x < z and self.q.msg[k,5] >= self.tm:
                        w[-self.stm:] = w[-self.stm:] * self.trunk
                        b[t:t+x] = b[t:t+x] + w
                else:
                    if x >= y and self.q.msg[k,3] >= self.tm:
                        w = w[:y]
                        w[-self.stm:] = w[-self.stm:] * self.trunk
                        x = w.shape[0]
                        b[t:t+x] = b[t:t+x] + w
                    elif x < y and self.q.msg[k,3] >= self.tm:
                        w[-self.stm:] = w[-self.stm:] * self.trunk
                        b[t:t+x] = b[t:t+x] + w
            except:
                print("error with reconstruction")
        b = self.scale(b)
        return np.vstack([b,b]).T

class parser():
    def __init__(self, midipath):
        mid = mido.MidiFile(midipath)
        _notes = []
        _vel = []
        _chan = []
        _trak = []
        self.tempo = [500000 / mid.ticks_per_beat * 1e-6]
        self.ttempo = [0]
        _kdur = []
        _ndur = []
        _inst = []

        for k in range(len(mid.tracks)):
            ttime = 0
            ktime = 0
            for m in mid.tracks[k]:
                channel = float('nan')
                note = float('nan')
                vel = float('nan')
                ndur = float('nan')
                ttime = ttime + m.time
                ctempo = self.tempo[self.tempo_lookup(ttime)]
                ktime = ktime + (m.time * ctempo)

                if m.type == 'note_on':
                    if m.velocity != 0:
                        channel = m.channel
                        note = m.note
                        vel = m.velocity

                    elif m.velocity == 0:
                        h = np.argwhere(np.array(_notes) == m.note)[-1,0]
                        _ndur[h] = ktime - _kdur[h]

                elif m.type == 'set_tempo':
                    self.tempo.append(m.tempo / mid.ticks_per_beat * 1e-6)
                    self.ttempo.append(ttime)

                elif m.type == 'program_change':
                    _inst.append((m.channel,m.program))

                _notes.append(note)
                _chan.append(channel)
                _trak.append(k)
                _vel.append(vel)
                _kdur.append(ktime)
                _ndur.append(ndur)

        self.msg = np.array([_trak,_chan,_notes,_vel,_ndur,_kdur]).T
        self.msg = self.msg[~np.isnan(self.msg).any(axis=1)]
        self.avail_dur()
        self.inst = dict(_inst)

    def tempo_lookup(self, ttime):
        return np.argwhere(np.array(self.ttempo) <= ttime)[-1,0]

    def avail_dur(self):
        self.mx = np.max(self.msg[:,4] + self.msg[:,5])
        q = []
        trak = np.unique(self.msg[:,0]) #unique tracks
        for k in trak:
            w = self.msg[self.msg[:,0] == k] #unique track k
            u = np.unique(w[:,2]) #unique notes in that track
            for m in u:
                z = w[w[:,2] == m] #array of only those notes within track k
                h = np.diff(np.append(z[:,5],[self.mx]))
                q.append(np.hstack([z,h.reshape([-1,1])]))
        self.msg = np.vstack(q)[:,1:]

def convert(convert_from, convert_to, freq=44100):
    '''convert from mp3 or wav to any other format at a specified frequency'''
    string = 'ffmpeg -i ' + '\"' + convert_from + '\"' + ' -ar ' + str(freq) + ' ' + '\"' + convert_to + '\"' + ' -y'
    os.system(string)

# Example usage code commented out - use as module instead
# dlink = '/content/gdrive/My Drive/mp5/midi/midi_files/'
# link = dlink + mid_file
# x = midi_io()
# x.midi_msg(link)

# slink = mid_file.split('.w')[0]
# write(dlink + slink + '.wav', 44100, x.reco())
# convert(dlink + slink + '.wav', dlink + slink + '.mp3')
# os.remove(dlink + slink + '.wav')