# https://en.wikipedia.org/wiki/General_MIDI_Level_2
'''returns dictionary:
            name of instrument (string value),
            does instrument decay (True / False),
            does is decay interupted (True / False) '''

table = {1: ['acounstic grand piano', True, True], 
                    2: ['bright acoustic piano', True, True],
                    3: ['electric grand piano', False, True],
                    4: ['honky-tonk piano', True, True],
                    5: ['electric piano 1', False, True],
                    6: ['electric piano 2', False, True],
                    7: ['harpsichord', True, True],
                    8: ['clavinet', False, True],
                    9: ['celesta', True, True],
                    10: ['glockenspiel', True, True],
                    11: ['music box', True, True],
                    12: ['Vibraphones', True, True],
                    13: ['Marimbas', True, True],
                    14: ['Xylophones', True, True],
                    15: ['Tubular Bells', True, True],
                    16: ['Dulcimer/Santur', True, True],
                    17: ['Drawbar Organ 1', False, True],
                    18: ['Percussive B3 Organ 1', False, True],
                    19: ['Rock Organ', False, True],
                    20: ['Church Organ 1', False, True],
                    21: ['Reed Organ', False, True],
                    22: ['French Accordion', False, False],
                    23: ['Harmonica', False, False],
                    24: ['Bandoneon', False, False],
                    25: ['Nylon-Strings Guitar 1', False, False],
                    26: ['Steel-Strings Guitar', False, False],
                    27: ['Jazz Guitar', False, False],
                    28: ['Clean Electric Guitar', True, False],
                    29: ['Muted Electric Guitar', False, False],
                    30: ['Overdriven Guitar', False, False],
                    31: ['Distortion Guitar', False, False],
                    32: ['Guitar Harmonics', True, False],
                    33: ['Acoustic Bass', True, False],
                    34: ['Fingered Bass', True, False],
                    35: ['Picked Bass', True, False],
                    36: ['Fretless Bass', True, False],
                    37: ['Slapped Bass 1', True, False],
                    38: ['Slapped Bass 2', True, False],
                    39: ['Synth-Bass 1', False, True],
                    40: ['Synth-Bass 2', False, True],
                    41: ['Violin', False, False],
                    42: ['Viola', False, False],
                    43: ['Cello', False, False],
                    44: ['Contrabass', False, False],
                    45: ['Tremelo', False, False],
                    46: ['Pizzicato', True, False],
                    47: ['Harp', True, True],
                    48: ['Timpani', True, False],
                    49: ['Strings Ensemble 1', False, False],
                    50: ['Strings Ensemble 2', False, False],
                    51: ['Synth-Strings 1', False, False],
                    52: ['Synth-Strings 2', False, False],
                    53: ['Choir Aahs 1', False, False],
                    54: ['Voice Oohs', False, False],
                    55: ['Synth-Voices', False, False],
                    56: ['Orchestral Hits', False, False],
                    57: ['Trumpet', False, False],
                    58: ['Trombone 1', False, False],
                    59: ['Tuba', False, False],
                    60: ['Muted Trumpet 1', False, False],
                    61: ['French Horns 1', False, False],
                    62: ['Brass Section 1', False, False],
                    63: ['Synth-Brass 1', False, False],
                    64: ['Synth-Brass 2', False, False],
                    65: ['Soprano Saxophone', False, False],
                    66: ['Alto Saxophone', False, False],
                    67: ['Tenor Saxophone', False, False],
                    68: ['Baritone Saxophone', False, False],
                    69: ['Oboe', False, False],
                    70: ['English Horn', False, False],
                    71: ['Bassoon', False, False],
                    72: ['Clarinet', False, False],
                    73: ['Piccolo', False, False],
                    74: ['Flute', False, False],
                    75: ['Recorder', False, False],
                    76: ['Pan Flutes', False, False],
                    77: ['Bottles Blown Flutes', False, False],
                    78: ['Shakuhachi', False, False],
                    79: ['Whistle', False, False],
                    80: ['Ocarina', False, False],
                    81: ['Square Lead', False, False],
                    82: ['Saw Lead', False, False],
                    83: ['Synth Calliope', False, False],
                    84: ['Chiffer Lead', False, False],
                    85: ['Charang', True, False],
                    86: ['Solo Synth Vox', False, False],
                    87: ['5th Saw Wave', False, False],
                    88: ['Bass & Lead', True, False],
                    89: ['Fantasia Pad', True, True],
                    90: ['Warm Pad', True, True],
                    91: ['made up', False, False],
                    92: ['made up', False, False],
                    93: ['made up', False, False],
                    94: ['made up', False, False],
                    95: ['made up', False, False],
                    96: ['made up', False, False],
                    97: ['made up', False, False],
                    98: ['made up', False, False],
                    99: ['made up', False, False],
                    100: ['made up', False, False],
                    101: ['made up', False, False],
                    102: ['made up', False, False],
                    103: ['made up', False, False],
                    104: ['made up', False, False],
                    105: ['made up', False, False],
                    106: ['made up', False, False],
                    107: ['made up', False, False],
                    108: ['made up', False, False],
                    109: ['made up', False, False],
                    110: ['made up', False, False],
                    111: ['made up', False, False],
                    112: ['made up', False, False],
                    113: ['made up', False, False],
                    114: ['made up', False, False],
                    115: ['made up', False, False],
                    116: ['made up', False, False],
                    117: ['made up', False, False],
                    118: ['made up', False, False],
                    119: ['made up', False, False],
                    120: ['made up', False, False],
                    121: ['made up', False, False],
                    122: ['made up', False, False],
                    123: ['made up', False, False],
                    124: ['made up', False, False],
                    125: ['made up', False, False],
                    126: ['made up', False, False],
                    127: ['made up', False, False]}
